### PR TITLE
Fixes for EKS

### PR DESCRIPTION
**Pull request by rkruze**
Fixed up the DNS names to match what was seen. Which was similar to
redpanda-0.redpanda.redpanda.svc.cluster.local. This could probably be
cleaned up.

Also added the rpc port to the headless service and said to publish not
ready addresses.

### CODE REVIEW

**Comment by oranda** [comment]
I think you said you are still working on this, so let me know when you're ready and I'll test.

**Comment by rkruze** [comment]
I've cleaned this up and remove items that were not needed to get this to work. @BenPope might have further comments.

**Comment by BenPope** [comment]
I don't understand the fix, but it  looks ok to me.

This breaks my use on KinD, but I don't know why (I changed `/etc/ hosts` to use the FQDN): https://github.com/BenPope/deployment-automation/tree/kubernetes-kind/kubernetes/kind

But that's less important than having it work on EKS - just bear it in mind if you set up a LoadBalancer.

**Comment by BenPope** [comment]
So I think it breaks for the same reason that the kafka API can't be reached from another namespace.

**Comment by oranda** [comment]
I was able to test these changes on `us-west-1`. I can confirm that the problem has gone away: the brokers are now communicating with each other on EKS just the same way they do locally. 

Also, despite what Ben said, it seems things continue to work for me locally (with kind).

**Comment by BenPope** [comment]
> Also, despite what Ben said, it seems things continue to work for me locally (with kind).

My bad - my kind cluster moved IP range

**Pull request merged**
